export type ScenarioCoverage = {
  routes: readonly string[]
  commands: readonly string[]
  updates: readonly string[]
  writes: readonly string[]
  jobs: readonly string[]
  errors: readonly string[]
}

export const scenarioCoverage = {
  chats: {
    routes: [
      'chats-page',
      'chat',
      'chat-paid-access',
      'chat-payment-type',
      'chat-change-price',
      'chat-custom-message',
      'chat-edit-custom-message',
      'chat-remove-custom-message',
      'chat-onchain-enable',
      'chat-onchain-disable',
    ],
    commands: ['/chats'],
    updates: [
      'my_chat_member',
      ':new_chat_title',
      'callback_query',
      'message',
      'chat_join_request',
    ],
    writes: [
      'users.insert',
      'chats.insert',
      'chats.update',
      'conversations.insert',
      'conversations.delete',
      'subscription_intents.insert',
      'subscription_payments.insert',
    ],
    jobs: [],
    errors: [],
  },
  errors: {
    routes: ['pay-subscription', 'subscription'],
    commands: ['/wallet'],
    updates: ['message', 'callback_query', 'hears', 'my_chat_member', 'chat_join_request'],
    writes: ['users.insert', 'users.update'],
    jobs: ['check-subscription-payments'],
    errors: [
      'insufficient_funds',
      'invoice_already_paid',
      'invoice_generation_failed',
      'invoice_parsing',
      'nwc_timeout',
      'nwc_connection',
      'nwc_payment_failed',
      'nwc_no_answer',
      'no_recipient',
      'to_bot',
      'from_bot',
      'to_yourself',
      'user_has_no_wallet',
      'not_found',
      'unknown',
    ],
  },
  http: {
    routes: [],
    commands: ['/wallet'],
    updates: ['message', 'hears'],
    writes: ['users.insert', 'pending_invoices.insert', 'pending_invoices.delete'],
    jobs: [],
    errors: ['invoice_parsing'],
  },
  input: {
    routes: ['chat', 'pay-subscription'],
    commands: [],
    updates: [
      'edited_message',
      'channel_post',
      'edited_channel_post',
      'poll',
      'poll_answer',
      'chat_member',
      'inline_query',
      'chosen_inline_result',
      'shipping_query',
      'pre_checkout_query',
      'message_reaction',
      'message',
      'callback_query',
      'chat_join_request',
      'hears',
    ],
    writes: [
      'users.insert',
      'users.update',
      'subscription_intents.insert',
      'subscription_payments.insert',
      'subscription_payments.update',
    ],
    jobs: [],
    errors: ['invoice_already_paid', 'not_found'],
  },
  invoices: {
    routes: [
      'create-invoice',
      'add-invoice-memo',
      'pay-invoice',
      'cancel',
      'connect-nwc',
      'send-to-user',
    ],
    commands: ['/wallet'],
    updates: ['callback_query', 'message', 'hears'],
    writes: [
      'users.insert',
      'conversations.insert',
      'conversations.delete',
      'pending_invoices.insert',
      'pending_invoices.delete',
    ],
    jobs: [],
    errors: [
      'insufficient_funds',
      'invoice_already_paid',
      'invoice_generation_failed',
      'invoice_parsing',
    ],
  },
  jobs: {
    routes: [],
    commands: [],
    updates: [],
    writes: [
      'pending_invoices.delete',
      'subscriptions.delete',
      'subscription_intents.delete',
      'subscription_payments.delete',
    ],
    jobs: [
      'check-pending-invoices',
      'delete-expired-invoices',
      'check-subscription-payments',
      'check-onchain-charges',
      'check-expired-subscriptions',
      'process-expiring-subscriptions',
      'process-monthly-donations',
    ],
    errors: [],
  },
  donations: {
    routes: [
      'donate',
      'donate-custom',
      'donate-monthly-menu',
      'donate-monthly-disable',
      'donate-monthly-custom',
      'donation-settings',
      'donation-custom-percent',
      'donation-percent',
      'donation-scope',
      'donate-amount',
      'donate-monthly-amount',
    ],
    commands: ['/donate'],
    updates: ['message', 'callback_query'],
    writes: [
      'users.insert',
      'users.update',
      'donations.insert',
      'donation_platform_stats.insert',
      'donation_platform_stats.update',
      'conversations.insert',
      'conversations.delete',
    ],
    jobs: ['process-monthly-donations'],
    errors: ['insufficient_funds'],
  },
  'feature-requests': {
    routes: ['feature-fund-amount', 'feature-fund-skip', 'feature-fund-custom', 'cancel'],
    commands: ['/feature'],
    updates: ['message', 'callback_query'],
    writes: [
      'users.insert',
      'donations.insert',
      'donation_platform_stats.insert',
      'donation_platform_stats.update',
      'conversations.insert',
      'conversations.delete',
    ],
    jobs: [],
    errors: [],
  },
  journeys: {
    routes: [
      'wallet',
      'settings',
      'help',
      'cancel',
      'send-menu',
      'send-to-user',
      'create-invoice',
      'chats-page',
      'chat',
      'chat-paid-access',
      'chat-payment-type',
      'chat-change-price',
      'chat-custom-message',
      'chat-edit-custom-message',
      'chat-remove-custom-message',
      'subscriptions-page',
      'subscription',
      'subscription-renew',
      'pay-subscription',
    ],
    commands: ['/start', '/wallet'],
    updates: ['message', 'callback_query', 'hears', 'my_chat_member', 'chat_join_request'],
    writes: [
      'users.insert',
      'chats.insert',
      'chats.update',
      'conversations.insert',
      'conversations.delete',
      'pending_invoices.insert',
      'pending_invoices.delete',
      'subscriptions.insert',
      'subscriptions.update',
      'subscriptions.delete',
      'subscription_intents.insert',
      'subscription_intents.delete',
      'subscription_payments.insert',
      'subscription_payments.update',
      'subscription_payments.delete',
    ],
    jobs: [
      'check-pending-invoices',
      'check-subscription-payments',
      'check-expired-subscriptions',
      'process-expiring-subscriptions',
    ],
    errors: [],
  },
  lifecycle: {
    routes: [],
    commands: [],
    updates: [],
    writes: [],
    jobs: [],
    errors: [],
  },
  nwc: {
    routes: ['connect-nwc', 'disconnect-nwc', 'toggle-nwc-tips', 'pay-subscription'],
    commands: ['/wallet', '/settings'],
    updates: ['message', 'callback_query', 'hears', 'chat_join_request'],
    writes: [
      'users.insert',
      'users.update',
      'conversations.insert',
      'conversations.delete',
      'subscription_intents.insert',
      'subscription_payments.insert',
      'subscription_payments.update',
    ],
    jobs: [],
    errors: [],
  },
  routing: {
    routes: [
      'wallet',
      'settings',
      'help',
      'cancel',
      'send-menu',
      'send-to-user',
      'pay-invoice',
      'create-invoice',
      'connect-nwc',
      'disconnect-nwc',
      'toggle-nwc-tips',
      'group-settings',
      'chats-page',
      'chat',
      'chat-paid-access',
      'chat-payment-type',
      'chat-change-price',
      'chat-custom-message',
      'chat-edit-custom-message',
      'chat-remove-custom-message',
      'subscriptions-page',
      'subscription',
      'subscription-renew',
      'pay-subscription',
      'donate',
      'donation-settings',
      'donation-percent',
      'donation-scope',
      'donate-amount',
      'donate-monthly-menu',
      'donate-monthly-amount',
      'donate-monthly-disable',
      'donate-custom',
      'donation-custom-percent',
      'donate-monthly-custom',
    ],
    commands: ['/start', '/help', '/wallet', '/settings', '/chats', '/subscriptions', '/donate'],
    updates: ['message', 'callback_query', 'hears'],
    writes: [
      'users.insert',
      'users.update',
      'chats.update',
      'conversations.insert',
      'subscriptions.update',
    ],
    jobs: [],
    errors: ['from_bot', 'not_found'],
  },
  'subscriptions-join': {
    routes: [],
    commands: [],
    updates: ['chat_join_request'],
    writes: [
      'users.insert',
      'subscription_intents.insert',
      'subscription_intents.update',
      'subscription_payments.insert',
      'subscription_payments.update',
    ],
    jobs: [],
    errors: [],
  },
  'onchain-join': {
    routes: ['pay-onchain', 'pay-lightning'],
    commands: [],
    updates: ['chat_join_request', 'callback_query'],
    writes: [
      'users.insert',
      'chats.update',
      'subscription_intents.insert',
      'subscription_intents.update',
      'subscription_payments.insert',
      'subscription_payments.update',
      'subscriptions.insert',
      'onchain_chat_payments.insert',
      'onchain_chat_payments.update',
      'onchain_chat_payments.delete',
    ],
    jobs: ['check-onchain-charges'],
    errors: [],
  },
  'subscriptions-renewal': {
    routes: ['pay-subscription'],
    commands: [],
    updates: ['callback_query'],
    writes: [
      'subscriptions.update',
      'subscriptions.delete',
      'subscription_intents.insert',
      'subscription_intents.delete',
      'subscription_payments.insert',
      'subscription_payments.update',
      'subscription_payments.delete',
    ],
    jobs: [
      'check-subscription-payments',
      'check-expired-subscriptions',
      'process-expiring-subscriptions',
    ],
    errors: [],
  },
  'subscriptions-settle': {
    routes: [],
    commands: [],
    updates: [],
    writes: [
      'users.insert',
      'subscriptions.insert',
      'subscriptions.update',
      'subscription_intents.update',
      'subscription_intents.delete',
      'subscription_payments.update',
      'subscription_payments.delete',
    ],
    jobs: ['check-subscription-payments'],
    errors: [],
  },
  tipping: {
    routes: ['send-to-user'],
    commands: [],
    updates: ['message', 'callback_query', 'hears'],
    writes: [
      'users.insert',
      'users.update',
      'conversations.insert',
      'conversations.delete',
      'donations.insert',
      'donation_platform_stats.insert',
      'donation_platform_stats.update',
    ],
    jobs: [],
    errors: ['insufficient_funds', 'no_recipient', 'to_bot', 'to_yourself', 'user_has_no_wallet'],
  },
  wallet: {
    routes: [
      'wallet',
      'settings',
      'group-settings',
      'toggle-nwc-tips',
      'send-menu',
      'donation-settings',
    ],
    commands: ['/wallet', '/settings'],
    updates: ['message', 'callback_query'],
    writes: ['users.update'],
    jobs: [],
    errors: ['unknown'],
  },
} as const satisfies Record<string, ScenarioCoverage>
